name: Deploy

on:
  push:
    branches:
      - master

jobs:
  - name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitLab
        uses: docker/login-action@v2
        with:
          registry: registry.hop.io
          username: ${{ secrets.HOP_REGISTRY_USERNAME }}
          password: ${{ secrets.HOP_REGISTRY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: streamticker/streamticker:latest
