name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node 18
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Install deps for CI
        run: yarn add @onehop/js

      - name: Pull environment variables
        run: node ./ci/pull-env.mjs
        env:
          HOP_API_KEY: ${{ secrets.HOP_API_KEY }}
          HOP_DEPLOYMENT_ID: deployment_MzMyMzc0ODA5MDAyNTU3NzQ

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Hop registry
        uses: docker/login-action@v2
        with:
          registry: registry.hop.io
          username: ${{ secrets.HOP_REGISTRY_USERNAME }}
          password: ${{ secrets.HOP_REGISTRY_PASSWORD }}

      - name: Build docker image
        run: docker build$(cat .env | while read line; do out+=" --build-arg $line"; done; echo $out; out="") . -t registry.hop.io/streamticker/streamticker:latest

      - name: Push docker image
        run: docker push registry.hop.io/streamticker/streamticker:latest
